"""quiz completion

Revision ID: dc696576a211
Revises: 9af458b1d567
Create Date: 2021-05-16 21:57:25.087673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc696576a211'
down_revision = '9af458b1d567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('completed_quiz', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'completed_quiz')
    # ### end Alembic commands ###
